### ISSUE TITLE
Error: invalid property: "resource"

### ISSUE THREAD

**Issue by skddc** [sockethub/sockethub-platform-xmpp#4]
I copied the code from the example, and it's crashing my entire SH instance. I'm pretty sure `resource` actually belongs there:

```
  socket.io:socket dispatching an event ["credentials",{"actor":"xmpp://hyper_rau@localhost","context":"xmpp","object":{"username":"hyper_rau","password":"123","server":"localhost","port":5222,"resource":"laptop"}}] +0ms
  sockethub:validate validating credentials +1ms

UNCAUGHT EXCEPTION - something horrible has happened!

Error: invalid property: "resource"
    at Object.Stream (/home/basti/src/sockethub/sockethub/node_modules/activity-streams/lib/activity-streams.js:101:13)
    at /home/basti/src/sockethub/sockethub/lib/validate.js:60:31
    at _callFunc (/home/basti/src/sockethub/sockethub/lib/middleware.js:29:18)
    at Socket.<anonymous> (/home/basti/src/sockethub/sockethub/lib/middleware.js:39:5)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at /home/basti/src/sockethub/sockethub/node_modules/socket.io/lib/socket.js:503:12
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
```

**Comment by skddc** [comment]
Hmm, same for the other properties.

**Comment by skddc** [comment]
Never mind, it was missing the type, because that's defined elsewhere in the example.

**Comment by skddc** [comment]
Actually, client input should never crash the whole instance, so this is still a bug in general. Not sure if here or for Sockethub core. Re-opening until we have the right issue in the right repo for it.

**Comment by silverbucket** [comment]
cool, thanks for the report. you are right it should never crash
